/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Companies */
        get: operations["get_companies_companies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Facets */
        get: operations["get_facets_facets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["get_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/postings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Postings */
        get: operations["get_postings_postings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/postings/{posting_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Posting Detail */
        get: operations["get_posting_detail_postings__posting_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/postings/{posting_id}/favorite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Favorite */
        post: operations["set_favorite_postings__posting_id__favorite_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/postings/{posting_id}/hide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Hidden */
        post: operations["set_hidden_postings__posting_id__hide_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AliasOut */
        AliasOut: {
            /** Seen At */
            seen_at: string;
            source: components["schemas"]["Source"];
            /** Source Job Id */
            source_job_id: string;
            /** Url */
            url: string;
        };
        /** CompanyOut */
        CompanyOut: {
            /** Company Name */
            company_name: string;
            /** Company Slug */
            company_slug: string;
            /** Enabled */
            enabled: boolean;
            /** Hq Country */
            hq_country: string;
            /** Last Ok At */
            last_ok_at: string | null;
            /** Postings Count */
            postings_count: number;
            /** Sector */
            sector: string;
            source: components["schemas"]["Source"];
        };
        /** CompensationOut */
        CompensationOut: {
            /** Amount Max */
            amount_max: string | null;
            /** Amount Min */
            amount_min: string | null;
            /** Bonus Mentioned */
            bonus_mentioned: boolean;
            /** Currency */
            currency: string | null;
            /** Equity Mentioned */
            equity_mentioned: boolean;
            period: components["schemas"]["SalaryPeriod"] | null;
            /** Raw */
            raw: string | null;
        };
        /** FacetCounts */
        FacetCounts: {
            /** Cities */
            cities: {
                [key: string]: number;
            };
            /** Companies */
            companies: {
                [key: string]: number;
            };
            /** Countries */
            countries: {
                [key: string]: number;
            };
            /** Sectors */
            sectors: {
                [key: string]: number;
            };
            /** Seniorities */
            seniorities: {
                [key: string]: number;
            };
            /** Sources */
            sources: {
                [key: string]: number;
            };
            /** Tech */
            tech: {
                [key: string]: number;
            };
        };
        /** FeedHealth */
        FeedHealth: {
            /** Active Postings */
            active_postings: number;
            /** Newest Posting Age H */
            newest_posting_age_h: number | null;
            /** Stale */
            stale: boolean;
        };
        /** FlagRequest */
        FlagRequest: {
            /** Value */
            value: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthAlert */
        HealthAlert: {
            /** Kind */
            kind: string;
            /** Since */
            since: string;
            /** Source */
            source: string | null;
        };
        /** HealthSnapshot */
        HealthSnapshot: {
            /** Alerts */
            alerts: components["schemas"]["HealthAlert"][];
            feed: components["schemas"]["FeedHealth"];
            /** Schema Version */
            schema_version: number;
            /** Sources */
            sources: components["schemas"]["SourceHealth"][];
        };
        /** LocationOut */
        LocationOut: {
            /** City */
            city: string | null;
            /** Country */
            country: string | null;
            /** Raw */
            raw: string | null;
            /** Region */
            region: string | null;
            remote_mode: components["schemas"]["RemoteMode"];
        };
        /** PostingDetailOut */
        PostingDetailOut: {
            /** Alias Count */
            alias_count: number;
            /** Aliases */
            aliases: components["schemas"]["AliasOut"][];
            /** Closes At */
            closes_at: string | null;
            /** Company Name */
            company_name: string;
            /** Company Slug */
            company_slug: string;
            compensation: components["schemas"]["CompensationOut"];
            /** Description */
            description: string | null;
            /** Favorited */
            favorited: boolean;
            /** First Seen At */
            first_seen_at: string;
            /** Hidden */
            hidden: boolean;
            /** Last Seen At */
            last_seen_at: string;
            /** Locations */
            locations: components["schemas"]["LocationOut"][];
            /** Min Years */
            min_years: number | null;
            /** Phd Required */
            phd_required: boolean;
            /** Posted At */
            posted_at: string | null;
            /** Posting Id */
            posting_id: string;
            /** Reasons */
            reasons: components["schemas"]["Reason"][];
            /** Rejection Reason */
            rejection_reason: string | null;
            role_family: components["schemas"]["RoleFamily"];
            /** Score */
            score: number;
            /** Sector */
            sector: string;
            seniority: components["schemas"]["Seniority"];
            source: components["schemas"]["Source"];
            /** Tech */
            tech: string[];
            tier: components["schemas"]["Tier"];
            /** Title */
            title: string;
            /** Title Raw */
            title_raw: string;
            /** Url */
            url: string;
            visa_sponsorship: components["schemas"]["VisaStatus"];
        };
        /** PostingOut */
        PostingOut: {
            /** Alias Count */
            alias_count: number;
            /** Closes At */
            closes_at: string | null;
            /** Company Name */
            company_name: string;
            /** Company Slug */
            company_slug: string;
            compensation: components["schemas"]["CompensationOut"];
            /** Favorited */
            favorited: boolean;
            /** First Seen At */
            first_seen_at: string;
            /** Hidden */
            hidden: boolean;
            /** Last Seen At */
            last_seen_at: string;
            /** Locations */
            locations: components["schemas"]["LocationOut"][];
            /** Min Years */
            min_years: number | null;
            /** Phd Required */
            phd_required: boolean;
            /** Posted At */
            posted_at: string | null;
            /** Posting Id */
            posting_id: string;
            role_family: components["schemas"]["RoleFamily"];
            /** Score */
            score: number;
            /** Sector */
            sector: string;
            seniority: components["schemas"]["Seniority"];
            source: components["schemas"]["Source"];
            /** Tech */
            tech: string[];
            tier: components["schemas"]["Tier"];
            /** Title */
            title: string;
            /** Title Raw */
            title_raw: string;
            /** Url */
            url: string;
            visa_sponsorship: components["schemas"]["VisaStatus"];
        };
        /** PostingsPage */
        PostingsPage: {
            /** Items */
            items: components["schemas"]["PostingOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** Reason */
        Reason: {
            /** Code */
            code: string;
            /** Delta */
            delta: number;
            /** Evidence */
            evidence: string | null;
        };
        /**
         * RemoteMode
         * @enum {string}
         */
        RemoteMode: "onsite" | "hybrid" | "remote" | "unknown";
        /**
         * RoleFamily
         * @enum {string}
         */
        RoleFamily: "quant_dev" | "quant_research" | "quant_trading" | "swe_platform" | "data_eng" | "risk" | "other";
        /**
         * SalaryPeriod
         * @enum {string}
         */
        SalaryPeriod: "year" | "month" | "day" | "hour";
        /**
         * Seniority
         * @enum {string}
         */
        Seniority: "intern" | "graduate" | "junior" | "mid" | "senior" | "lead" | "unknown";
        /**
         * SortKey
         * @enum {string}
         */
        SortKey: "score" | "posted" | "seen" | "company" | "closes";
        /**
         * Source
         * @enum {string}
         */
        Source: "greenhouse" | "lever" | "ashby" | "smartrecruiters" | "workable" | "recruitee" | "personio" | "workday" | "custom" | "efinancialcareers" | "wttj" | "linkedin" | "indeed";
        /** SourceHealth */
        SourceHealth: {
            /** Alert */
            alert?: string | null;
            /** Boards Error */
            boards_error?: number | null;
            /** Boards Ok */
            boards_ok?: number | null;
            /** Last Count */
            last_count?: number | null;
            /** Last Run At */
            last_run_at?: string | null;
            source: components["schemas"]["Source"];
            /** Status */
            status: string;
        };
        /**
         * Tier
         * @enum {string}
         */
        Tier: "strong" | "possible" | "stretch" | "rejected";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VisaStatus
         * @enum {string}
         */
        VisaStatus: "sponsors" | "no" | "unknown";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_companies_companies_get: {
        parameters: {
            query?: {
                sector?: string | null;
                country?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_facets_facets_get: {
        parameters: {
            query?: {
                countries?: string[];
                cities?: string[];
                companies?: string[];
                sectors?: string[];
                sources?: components["schemas"]["Source"][];
                role_families?: components["schemas"]["RoleFamily"][];
                seniorities?: components["schemas"]["Seniority"][];
                remote_modes?: components["schemas"]["RemoteMode"][];
                tech_all?: string[];
                tech_any?: string[];
                visa?: components["schemas"]["VisaStatus"][];
                min_score?: number;
                tiers?: components["schemas"]["Tier"][];
                posted_within_days?: number | null;
                query?: string | null;
                favorites_only?: boolean;
                include_hidden?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacetCounts"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthSnapshot"];
                };
            };
        };
    };
    get_postings_postings_get: {
        parameters: {
            query?: {
                sort?: components["schemas"]["SortKey"];
                cursor?: string | null;
                limit?: number;
                countries?: string[];
                cities?: string[];
                companies?: string[];
                sectors?: string[];
                sources?: components["schemas"]["Source"][];
                role_families?: components["schemas"]["RoleFamily"][];
                seniorities?: components["schemas"]["Seniority"][];
                remote_modes?: components["schemas"]["RemoteMode"][];
                tech_all?: string[];
                tech_any?: string[];
                visa?: components["schemas"]["VisaStatus"][];
                min_score?: number;
                tiers?: components["schemas"]["Tier"][];
                posted_within_days?: number | null;
                query?: string | null;
                favorites_only?: boolean;
                include_hidden?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostingsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_posting_detail_postings__posting_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                posting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostingDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_favorite_postings__posting_id__favorite_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                posting_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlagRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_hidden_postings__posting_id__hide_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                posting_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlagRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
